if (typeof window.__scraperV5Injected === 'undefined') {
window.__scraperV5Injected = true;
let isInspecting=false, hoveredElement=null, highlightOverlay=null, multiHighlightOverlays=[], layoutMutationObserver=null, visualIndicatorBadge=null, modeStatusFloatingBadge=null, selectorTuningBar=null, selectorTuningValueLabel=null, selectorTuningPreviewLabel=null, selectorTuningCountLabel=null, selectorTuningInput=null, currentActiveSelector='', currentResolvedNodes=[], currentSelectorCandidates=[], currentSelectorCandidateIndex=0, isWritingBatch=false;
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  try {
    if (message.type === 'PING') { sendResponse({ status: 'ALIVE' }); return true; }
    if (message.type === 'TOGGLE_INSPECTOR') { isInspecting=!!message.status; if (isInspecting) startInspector(); else stopInspector(); sendResponse({ success:true }); return true; }
  } catch (err) { sendResponse({ success:false, error: err.message }); return false; }
  return false;
});
const norm=t=>String(t||'').replace(/\s+/g,' ').trim();
function decodeBase64Unicode(str){ try { return decodeURIComponent(Array.prototype.map.call(atob(str), c => '%' + ('00'+c.charCodeAt(0).toString(16)).slice(-2)).join('')); } catch(e){ try { return atob(str); } catch(_){ return ''; } } }
function parseHashRoute(){ const rawHash=String(window.location.hash||''); const withoutHash=rawHash.startsWith('#')?rawHash.slice(1):rawHash; const [pathPart, queryString='']=withoutHash.split('?'); return { rawHash, routePath:pathPart||'/', params:new URLSearchParams(queryString||''), queryString }; }
function parseZoomInfoQueryPayload(){ const { params } = parseHashRoute(); const encodedQuery=params.get('query')||''; if(!encodedQuery) return null; try { return JSON.parse(decodeBase64Unicode(decodeURIComponent(encodedQuery))); } catch(e){ return null; } }
function getVirtualPath(){ const { routePath, queryString } = parseHashRoute(); return `#${routePath}${queryString ? `?${queryString}` : ''}`; }
function getPageKey(){ return getVirtualPath(); }
function getPageNumber(){ const payload=parseZoomInfoQueryPayload(); if(payload&&payload.filters&&payload.filters.page!=null) return String(payload.filters.page); const { params } = parseHashRoute(); return String(params.get('page') || '1'); }
function getSearchFingerprint(){ const { routePath, params } = parseHashRoute(); const payload=parseZoomInfoQueryPayload(); if(payload){ const clone = JSON.parse(JSON.stringify(payload)); if (clone.filters && Object.prototype.hasOwnProperty.call(clone.filters,'page')) delete clone.filters.page; return `#${routePath}?query=${JSON.stringify(clone)}`; } const pairs=[]; params.forEach((v,k)=>{ if(k==='page') return; pairs.push([k,v]); }); pairs.sort((a,b)=>String(a[0]).localeCompare(String(b[0])) || String(a[1]).localeCompare(String(b[1]))); const q=pairs.map(([k,v])=>`${encodeURIComponent(k)}=${encodeURIComponent(v)}`).join('&'); return `#${routePath}${q ? `?${q}` : ''}`; }
function getCaptureSessionKey(){ return `${window.location.hostname}__${getSearchFingerprint()}`; }
function escapeHtml(str){ return String(str||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;'); }
function extractNodeText(node){ return node ? norm(node.innerText || node.textContent || '') : ''; }
function getCellColumnIndex(el){ if(!el) return -1; const cell = el.closest && el.closest('td,th'); if(!cell || !cell.parentElement) return -1; return Array.from(cell.parentElement.children).indexOf(cell); }
function getTableColumnSelector(el){ const idx = getCellColumnIndex(el); if(idx < 0) return ''; const table = el.closest && el.closest('table'); if(!table) return ''; const tableSel = buildSimpleSelector(table); return tableSel ? tableSel + ' tbody tr > *:nth-child(' + (idx+1) + ')' : ''; }
function createOverlay(){ if(highlightOverlay) return; highlightOverlay=document.createElement('div'); highlightOverlay.style.position='absolute'; highlightOverlay.style.backgroundColor='rgba(0,123,255,0.18)'; highlightOverlay.style.border='2px solid #007bff'; highlightOverlay.style.pointerEvents='none'; highlightOverlay.style.zIndex='2147483647'; document.body.appendChild(highlightOverlay); }
function clearMultiOverlays(){ multiHighlightOverlays.forEach(d=>d&&d.remove()); multiHighlightOverlays=[]; }
function createModeStatusFloatingBadge(){ if(modeStatusFloatingBadge) return; modeStatusFloatingBadge=document.createElement('div'); modeStatusFloatingBadge.style.position='fixed'; modeStatusFloatingBadge.style.top='12px'; modeStatusFloatingBadge.style.left='50%'; modeStatusFloatingBadge.style.transform='translateX(-50%)'; modeStatusFloatingBadge.style.padding='10px 16px'; modeStatusFloatingBadge.style.borderRadius='8px'; modeStatusFloatingBadge.style.fontSize='14px'; modeStatusFloatingBadge.style.fontFamily='Arial,sans-serif'; modeStatusFloatingBadge.style.fontWeight='bold'; modeStatusFloatingBadge.style.zIndex='2147483647'; modeStatusFloatingBadge.style.boxShadow='0 4px 12px rgba(0,0,0,0.3)'; modeStatusFloatingBadge.style.pointerEvents='none'; modeStatusFloatingBadge.innerHTML='🔍 Inspect Mode | [/] multi-element'; modeStatusFloatingBadge.style.backgroundColor='#212121'; modeStatusFloatingBadge.style.color='#ffffff'; document.body.appendChild(modeStatusFloatingBadge); }
function createSelectorTuningBar(){ if(selectorTuningBar) return; selectorTuningBar=document.createElement('div'); selectorTuningBar.id='extension-selector-tuning-bar'; selectorTuningBar.style.position='fixed'; selectorTuningBar.style.top='58px'; selectorTuningBar.style.left='50%'; selectorTuningBar.style.transform='translateX(-50%)'; selectorTuningBar.style.width='min(860px, calc(100vw - 32px))'; selectorTuningBar.style.padding='12px 14px'; selectorTuningBar.style.borderRadius='12px'; selectorTuningBar.style.background='rgba(20,20,28,0.96)'; selectorTuningBar.style.color='#fff'; selectorTuningBar.style.fontFamily='Arial,sans-serif'; selectorTuningBar.style.fontSize='12px'; selectorTuningBar.style.lineHeight='1.45'; selectorTuningBar.style.zIndex='2147483647'; selectorTuningBar.style.boxShadow='0 10px 30px rgba(0,0,0,0.32)'; selectorTuningBar.style.border='1px solid rgba(255,255,255,0.12)'; selectorTuningBar.innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:8px;"><div style="font-weight:700;">Selector Precision</div><div id="extension-selector-tuning-value" style="font-weight:700;color:#8ab4ff;">Waiting for hover...</div></div><div style="display:flex;align-items:center;gap:10px;"><span style="white-space:nowrap;color:#c6dafc;">Precise</span><input id="extension-selector-tuning-range" type="range" min="0" max="0" value="0" style="flex:1;" /><span style="white-space:nowrap;color:#c6dafc;">Broad</span></div><div id="extension-selector-tuning-count" style="margin-top:8px;color:#c3e88d;">Matches 0</div><div id="extension-selector-tuning-preview" style="margin-top:6px;max-height:72px;overflow:auto;padding:8px 10px;border-radius:8px;background:rgba(255,255,255,0.06);font-family:Consolas, Monaco, monospace;word-break:break-word;"></div>`; document.body.appendChild(selectorTuningBar); selectorTuningValueLabel=selectorTuningBar.querySelector('#extension-selector-tuning-value'); selectorTuningPreviewLabel=selectorTuningBar.querySelector('#extension-selector-tuning-preview'); selectorTuningCountLabel=selectorTuningBar.querySelector('#extension-selector-tuning-count'); selectorTuningInput=selectorTuningBar.querySelector('#extension-selector-tuning-range'); selectorTuningInput.addEventListener('input',()=>{ currentSelectorCandidateIndex=Number(selectorTuningInput.value||0); applyCurrentSelectorCandidate(); }); }
function updateSelectorTuningBar(){ if(!selectorTuningBar || !selectorTuningInput) return; const total=currentSelectorCandidates.length; if(!total){ selectorTuningInput.min='0'; selectorTuningInput.max='0'; selectorTuningInput.value='0'; selectorTuningValueLabel.textContent='Waiting for hover...'; selectorTuningCountLabel.textContent='Matches 0'; selectorTuningPreviewLabel.textContent=''; return; } selectorTuningInput.min='0'; selectorTuningInput.max=String(Math.max(total-1,0)); selectorTuningInput.value=String(currentSelectorCandidateIndex); const c=currentSelectorCandidates[currentSelectorCandidateIndex]; selectorTuningValueLabel.textContent=`${currentSelectorCandidateIndex+1}/${total} • ${c.label}`; selectorTuningCountLabel.textContent=`Matches ${c.matchCount}`; selectorTuningPreviewLabel.textContent=c.selector; }
function startInspector(){ currentActiveSelector=''; currentResolvedNodes=[]; currentSelectorCandidates=[]; currentSelectorCandidateIndex=0; createOverlay(); createModeStatusFloatingBadge(); createSelectorTuningBar(); document.body.style.cursor='crosshair'; document.addEventListener('mousemove', handleMouseMove, true); document.addEventListener('click', handleElementClick, true); document.addEventListener('keydown', handleKeyDown, true); }
function stopInspector(){ isInspecting=false; document.body.style.cursor='default'; document.removeEventListener('mousemove', handleMouseMove, true); document.removeEventListener('click', handleElementClick, true); document.removeEventListener('keydown', handleKeyDown, true); if(highlightOverlay){highlightOverlay.remove(); highlightOverlay=null;} if(modeStatusFloatingBadge){modeStatusFloatingBadge.remove(); modeStatusFloatingBadge=null;} if(selectorTuningBar){selectorTuningBar.remove(); selectorTuningBar=null;} clearMultiOverlays(); hoveredElement=null; }
function getUsableClasses(el){ if(!el||!el.classList) return []; return Array.from(el.classList).filter(c=>typeof c==='string' && c.length<=45 && c!=='extension-multi-inspect-overlay-item' && !/^[0-9a-fA-F]{8,}$/.test(c)); }
function getStableAttributes(el){ if(!el || !el.getAttributeNames) return []; return el.getAttributeNames().filter(name => ['data-id','data-testid','data-test','aria-label','name','title','role'].includes(name)).map(name => [name, el.getAttribute(name)]).filter((pair) => pair[1] && String(pair[1]).trim().length); }
function buildIdSelector(el){ const id = el && el.id ? String(el.id).trim() : ''; return id ? '#' + CSS.escape(id) : ''; }
function buildAttrSelectors(el){ return getStableAttributes(el).map(([name,val]) => el.tagName.toLowerCase() + '[' + name + '="' + String(val).replace(/"/g,'\"') + '"]').filter(Boolean); }
function buildSimpleSelector(el){ if(!el||!el.tagName) return ''; const tag=el.tagName.toLowerCase(); const classes=getUsableClasses(el); return `${tag}${classes.length ? '.' + classes.slice(0,2).join('.') : ''}`; }
function buildExactSelector(el){ if(!el) return ''; if(el===document.body) return 'body'; if(el===document.documentElement) return 'html'; const selectorToken=buildSimpleSelector(el); if(!selectorToken) return ''; if(el.parentElement && el.parentElement!==document.documentElement && el.parentElement!==document.body){ let index=1, sibling=el.previousElementSibling; while(sibling){ if(sibling.tagName===el.tagName) index+=1; sibling=sibling.previousElementSibling; } return `${buildExactSelector(el.parentElement)} > ${selectorToken}:nth-of-type(${index})`; } const rootPrefix=el.parentElement===document.body?'body > ':''; return `${rootPrefix}${selectorToken}`; }
function getNodesForSelector(selector, fallback){ try { if(!selector) return fallback ? [fallback] : []; const matched=Array.from(document.querySelectorAll(selector)).filter(n=>n && n.getBoundingClientRect && n.getBoundingClientRect().width>0 && n.getBoundingClientRect().height>0); return matched.length ? matched : (fallback ? [fallback] : []); } catch(e){ return fallback ? [fallback] : []; } }
function buildSelectorCandidates(element){
  if(!element) return [];
  const candidates=[];
  const tag=element.tagName ? element.tagName.toLowerCase() : '';
  const idSel=buildIdSelector(element);
  const exact=buildExactSelector(element);
  const simple=buildSimpleSelector(element);
  const classes=getUsableClasses(element);
  const class1 = tag && classes[0] ? tag + '.' + classes[0] : '';
  const class2 = tag && classes.length > 1 ? tag + '.' + classes.slice(0,2).join('.') : '';
  const nthOfType = element.parentElement ? (() => { let i=1, sib=element.previousElementSibling; while(sib){ if(sib.tagName===element.tagName) i++; sib=sib.previousElementSibling; } return buildSimpleSelector(element.parentElement) + ' > ' + tag + ':nth-of-type(' + i + ')'; })() : '';
  const rowish=element.closest ? element.closest('tr, li, [role="row"], article, section, div') : null;
  const rowSelector = rowish ? buildSimpleSelector(rowish) : '';
  const parent = element.parentElement ? buildSimpleSelector(element.parentElement) : '';
  const attrs=buildAttrSelectors(element);
  const tableColSel = getTableColumnSelector(element);
  const cellOnly = element.closest ? element.closest('td,th') : null;
  const add=(selector,label)=>{ if(!selector || candidates.some(c=>c.selector===selector)) return; const nodes=getNodesForSelector(selector, element); if(nodes.length) candidates.push({selector,label,matchCount:nodes.length,nodes}); };
  add(tableColSel,'Table column only');
  add(idSel,'Unique id');
  attrs.forEach((s,i)=>add(s,'Stable attr ' + (i+1)));
  add(exact,'Exact element');
  add(class1,'Single class');
  add(class2,'Two classes');
  add(nthOfType,'Nth-of-type');
  add(simple,'Simple element');
  add(rowSelector,'Row/container');
  add(parent,'Parent container');
  add(tag,'Tag only');
  if(cellOnly) add('td, th', 'Cell generic');
  return candidates.sort((a,b)=>a.matchCount-b.matchCount || a.selector.length-b.selector.length);
}
function applyCurrentSelectorCandidate(){ const c=currentSelectorCandidates[currentSelectorCandidateIndex]; if(!c){ currentActiveSelector=''; currentResolvedNodes=hoveredElement?[hoveredElement]:[]; updateSelectorTuningBar(); clearMultiOverlays(); return; } currentActiveSelector=c.selector; currentResolvedNodes=c.nodes || []; updateSelectorTuningBar(); drawMultiModePreview(); }
function drawMultiModePreview(){ clearMultiOverlays(); if(!currentResolvedNodes || !currentResolvedNodes.length) return; if(currentResolvedNodes.length===1) return; currentResolvedNodes.forEach((node, idx)=>{ if(idx===0) return; const rect=node.getBoundingClientRect(); if(rect.width<=0 || rect.height<=0) return; const overlay=document.createElement('div'); overlay.style.position='absolute'; overlay.style.backgroundColor='rgba(233,30,99,0.16)'; overlay.style.border='1px dashed #e91e63'; overlay.style.pointerEvents='none'; overlay.style.zIndex='2147483646'; overlay.style.width=`${rect.width}px`; overlay.style.height=`${rect.height}px`; overlay.style.top=`${rect.top+window.scrollY}px`; overlay.style.left=`${rect.left+window.scrollX}px`; document.body.appendChild(overlay); multiHighlightOverlays.push(overlay); }); }
function handleMouseMove(e){ if(!isInspecting) return; e.stopPropagation(); const element=e.target; if(!element || element===document.body || element===document.documentElement) return; hoveredElement=element; const rect=element.getBoundingClientRect(); if(highlightOverlay){ highlightOverlay.style.width=`${rect.width}px`; highlightOverlay.style.height=`${rect.height}px`; highlightOverlay.style.top=`${rect.top+window.scrollY}px`; highlightOverlay.style.left=`${rect.left+window.scrollX}px`; } currentSelectorCandidates=buildSelectorCandidates(element); if(!currentSelectorCandidates.length){ currentSelectorCandidates=[{selector:buildExactSelector(element),label:'Fallback',matchCount:1,nodes:[element]}]; } currentSelectorCandidateIndex=0; applyCurrentSelectorCandidate(); }
function handleKeyDown(e){ if(!isInspecting) return; if(e.key==='['){ e.preventDefault(); e.stopPropagation(); currentSelectorCandidateIndex=Math.max(0,currentSelectorCandidateIndex-1); applyCurrentSelectorCandidate(); } if(e.key===']'){ e.preventDefault(); e.stopPropagation(); currentSelectorCandidateIndex=Math.min(currentSelectorCandidates.length-1,currentSelectorCandidateIndex+1); applyCurrentSelectorCandidate(); } }
function normalizeEndpointValue(endpoint){ let value=String(endpoint||'').trim(); if(!value) return ''; try { if(/^https?:\/\//i.test(value)){ const url=new URL(value); value=url.hash || url.pathname || '/'; } } catch(e){} if(value.startsWith('/#/')) value=value.slice(1); return value; }
function findMatchingEndpoint(endpoints){ const currentRoute=getVirtualPath().split('?')[0].replace(/^\/#/,'#'); return (endpoints || []).find(endpoint=>{ const clean=normalizeEndpointValue(endpoint).split('?')[0]; return clean && (currentRoute===clean || currentRoute.startsWith(clean) || clean.startsWith(currentRoute)); }) || currentRoute; }
function buildEntry(item){ return `${item.captureSessionKey}__${item.pageNumber}__${item.baseSelector}__${item.itemIndex}__${item.text}`; }
function saveElements(elements, cb){ chrome.storage.local.set({ scrapedElements: elements }, () => { const err=chrome.runtime.lastError; if(err){ cb(false, err.message || 'Storage write failed'); return; } chrome.storage.local.get(['scrapedElements'], verify => cb(true, (verify.scrapedElements || []).length)); }); }
function setStatus(success, title, detail, list){ if(!visualIndicatorBadge){ visualIndicatorBadge=document.createElement('div'); visualIndicatorBadge.style.position='fixed'; visualIndicatorBadge.style.bottom='16px'; visualIndicatorBadge.style.right='16px'; visualIndicatorBadge.style.minWidth='270px'; visualIndicatorBadge.style.maxWidth='420px'; visualIndicatorBadge.style.padding='12px 14px'; visualIndicatorBadge.style.borderRadius='14px'; visualIndicatorBadge.style.fontFamily='Arial,sans-serif'; visualIndicatorBadge.style.fontSize='12px'; visualIndicatorBadge.style.lineHeight='1.45'; visualIndicatorBadge.style.boxShadow='0 8px 24px rgba(0,0,0,0.18)'; visualIndicatorBadge.style.zIndex='2147483647'; visualIndicatorBadge.style.whiteSpace='normal'; visualIndicatorBadge.style.wordBreak='break-word'; document.body.appendChild(visualIndicatorBadge); } const items=(list||[]).filter(Boolean).slice(0,10).map(x=>`<div style="margin-top:4px;">• ${escapeHtml(x)}</div>`).join(''); visualIndicatorBadge.innerHTML=`<div style="display:flex;align-items:center;gap:8px;font-weight:bold;margin-bottom:6px;">${success ? '<span>✅</span><span>All elements captured</span>' : '<span>❌</span><span>Missing columns</span>'}</div><div style="font-weight:700;margin-bottom:4px;">${escapeHtml(title || '')}</div><div>${escapeHtml(detail || '')}</div>${items ? `<div style="margin-top:8px;">${items}</div>` : ''}`; visualIndicatorBadge.style.backgroundColor=success ? '#e6f4ea' : '#fce8e6'; visualIndicatorBadge.style.color=success ? '#137333' : '#c5221f'; visualIndicatorBadge.style.border=`1px solid ${success ? '#137333' : '#c5221f'}`; }
function handleElementClick(e){ if(!isInspecting || isWritingBatch) return; e.preventDefault(); e.stopPropagation(); isWritingBatch=true; const finalSelector=currentActiveSelector || buildExactSelector(hoveredElement); const selectedNodes=(currentResolvedNodes && currentResolvedNodes.length ? currentResolvedNodes : [hoveredElement]).filter(Boolean); chrome.storage.local.get(['endpoints','inspectionRules','scrapedElements'], result => { const endpoints=result.endpoints || []; const rules=result.inspectionRules || {}; const elements=result.scrapedElements || []; const matchedEndpoint=findMatchingEndpoint(endpoints); if(!rules[matchedEndpoint]) rules[matchedEndpoint]=[]; if(finalSelector && !rules[matchedEndpoint].includes(finalSelector)) rules[matchedEndpoint].push(finalSelector); let insertedCount=0; const missing=[]; selectedNodes.forEach((node, idx) => { const text=extractNodeText(node); if(!text){ missing.push(finalSelector); return; } const item={ text, selector:`${finalSelector}__${idx+1}`, baseSelector:finalSelector, itemIndex:idx+1, endpointOrigin:matchedEndpoint, domain:window.location.hostname, path:getPageKey(), searchFingerprint:getSearchFingerprint(), captureSessionKey:getCaptureSessionKey(), pageNumber:getPageNumber(), timestamp:new Date().toISOString() }; item.entryKey=buildEntry(item); if(!elements.some(x=>x.entryKey===item.entryKey)){ elements.push(item); insertedCount += 1; } }); chrome.storage.local.set({ inspectionRules: rules }, () => { saveElements(elements, (ok) => { setStatus(missing.length===0, missing.length===0 ? 'Captured successfully' : 'Some columns missing', missing.length===0 ? `Saved ${insertedCount} item(s)` : `Selected ${insertedCount} item(s)`, missing); chrome.runtime.sendMessage({ type:'INSPECTOR_DONE', insertedCount, selector: finalSelector, endpoint: matchedEndpoint, ok, missing }); isWritingBatch=false; stopInspector(); }); }); }); }
function refreshFromStoredRules(){ chrome.storage.local.get(['endpoints','inspectionRules','scrapedElements','columnNames'], result => { const endpoints=result.endpoints || []; const rules=result.inspectionRules || {}; const columnNames=result.columnNames || {}; const elements=result.scrapedElements || []; const matchedEndpoint=findMatchingEndpoint(endpoints); const pathRules=rules[matchedEndpoint] || []; if(!pathRules.length){ if(visualIndicatorBadge){ visualIndicatorBadge.remove(); visualIndicatorBadge=null; } return; } let changed=false; const missingItems=[]; pathRules.forEach(selector => { try { const nodes=Array.from(document.querySelectorAll(selector)); if(!nodes.length){ missingItems.push(columnNames[selector] || selector); return; } nodes.forEach((node, idx) => { const text=extractNodeText(node); if(!text) return; const item={ text, selector:`${selector}__${idx+1}`, baseSelector:selector, itemIndex:idx+1, endpointOrigin:matchedEndpoint, domain:window.location.hostname, path:getPageKey(), searchFingerprint:getSearchFingerprint(), captureSessionKey:getCaptureSessionKey(), pageNumber:getPageNumber(), timestamp:new Date().toISOString() }; item.entryKey=buildEntry(item); if(!elements.some(x=>x.entryKey===item.entryKey)){ elements.push(item); changed=true; } }); } catch(e){ missingItems.push(`${columnNames[selector] || selector} (invalid selector)`); } }); if(changed) saveElements(elements,()=>{}); setStatus(missingItems.length===0, missingItems.length===0 ? 'All elements captured' : 'Missing columns', missingItems.length===0 ? 'Every mapped column is visible on this page.' : 'Some mapped columns are not visible.', missingItems); if(layoutMutationObserver){ try { layoutMutationObserver.disconnect(); } catch(e){} } layoutMutationObserver=new MutationObserver(() => { if(!chrome.runtime || !chrome.runtime.id || isWritingBatch) return; refreshFromStoredRules(); }); layoutMutationObserver.observe(document.body,{ childList:true, subtree:true, characterData:true }); }); }
window.addEventListener('hashchange',()=>setTimeout(refreshFromStoredRules,250)); window.addEventListener('popstate',()=>setTimeout(refreshFromStoredRules,250)); refreshFromStoredRules();
}
